<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DASHLAPTOP" failures="1" tests="4" name="Test-Runner1" time="8.677" errors="0" timestamp="2023-11-27T15:10:29 IST">
  <testcase classname="com.TestNG.DemoTest" name="Demo1" time="0.044">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.TestNG.DemoTest.Demo1(DemoTest.java:13)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- Demo1 -->
  <testcase classname="com.TestNG.PracticeTest" name="practice1" time="0.01"/>
  <testcase classname="com.TestNG.DemoTest" name="Demo2" time="0.003"/>
  <testcase classname="com.TestNG.PracticeTest" name="practice2" time="0.027"/>
  <testcase classname="com.onlinebanking.kredvista.GenericUtils.BaseClass" name="@AfterSuite config_AS" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite config_AS -->
  <testcase classname="com.onlinebanking.kredvista.GenericUtils.BaseClass" name="@BeforeSuite config_DB" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite config_DB -->
</testsuite> <!-- Test-Runner1 -->
